// GENERATED by @edgedb/generate v0.4.1

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _sys_core from "./sys_core";
import type * as _sys_user from "./sys_user";
import type * as _std from "./std";
import type * as _app_cm from "./app_cm";
import type * as _cal from "./cal";
export type $CohortλShape = $.typeutil.flatten<_sys_core.$ObjλShape & {
  "codeStatus": $.LinkDesc<_sys_core.$Code, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "course": $.LinkDesc<$Course, $.Cardinality.One, {}, false, false,  false, false>;
  "staffAdmin": $.LinkDesc<_sys_user.$Staff, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "staffAgency": $.LinkDesc<_sys_user.$Staff, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "staffInstructor": $.LinkDesc<_sys_user.$Staff, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "venue": $.LinkDesc<_sys_core.$Org, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "capacity": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne, false, false, false, false>;
  "isCohortRequired": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "note": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "schedule": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "<cohort[is app_cm_training::CsfCohort]": $.LinkDesc<$CsfCohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<cohort": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Cohort = $.ObjectType<"app_cm_training::Cohort", $CohortλShape, null, [
  ..._sys_core.$Obj['__exclusives__'],
]>;
const $Cohort = $.makeType<$Cohort>(_.spec, "e62a3382-89f7-11ee-ae3b-89e851154f44", _.syntax.literal);

const Cohort: $.$expr_PathNode<$.TypeSet<$Cohort, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Cohort, $.Cardinality.Many), null);

export type $CourseλShape = $.typeutil.flatten<_sys_core.$ObjλShape & {
  "cost": $.PropertyDesc<_std.$float32, $.Cardinality.AtMostOne, false, false, false, false>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "isActive": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "schedule": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "codeMultiCerts": $.LinkDesc<_sys_core.$Code, $.Cardinality.Many, {}, false, false,  false, false>;
  "codeMultiExams": $.LinkDesc<_sys_core.$Code, $.Cardinality.Many, {}, false, false,  false, false>;
  "codeMultiItemsIncluded": $.LinkDesc<_sys_core.$Code, $.Cardinality.Many, {}, false, false,  false, false>;
  "codeMultiItemsNotIncluded": $.LinkDesc<_sys_core.$Code, $.Cardinality.Many, {}, false, false,  false, false>;
  "codeMultiRqmts": $.LinkDesc<_sys_core.$Code, $.Cardinality.Many, {}, false, false,  false, false>;
  "codeSector": $.LinkDesc<_sys_core.$Code, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "codeStatus": $.LinkDesc<_sys_core.$Code, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "codeTypePayment": $.LinkDesc<_sys_core.$CodeType, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "provider": $.LinkDesc<_sys_core.$Org, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "staffAdmin": $.LinkDesc<_sys_user.$Staff, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "staffAgency": $.LinkDesc<_sys_user.$Staff, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "<course[is app_cm_training::Cohort]": $.LinkDesc<$Cohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<course[is app_cm::CsfCertification]": $.LinkDesc<_app_cm.$CsfCertification, $.Cardinality.Many, {}, false, false,  false, false>;
  "<course": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Course = $.ObjectType<"app_cm_training::Course", $CourseλShape, null, [
  ..._sys_core.$Obj['__exclusives__'],
]>;
const $Course = $.makeType<$Course>(_.spec, "edb845d2-7d84-11ee-a1b3-051822eac25d", _.syntax.literal);

const Course: $.$expr_PathNode<$.TypeSet<$Course, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Course, $.Cardinality.Many), null);

export type $CsfCohortλShape = $.typeutil.flatten<_app_cm.$CsfDataλShape & {
  "codeStatus": $.LinkDesc<_sys_core.$Code, $.Cardinality.One, {}, false, false,  false, false>;
  "cohort": $.LinkDesc<$Cohort, $.Cardinality.One, {}, false, false,  false, false>;
  "dateEnd": $.PropertyDesc<_cal.$local_date, $.Cardinality.AtMostOne, false, false, false, false>;
  "dateStart": $.PropertyDesc<_cal.$local_date, $.Cardinality.AtMostOne, false, false, false, false>;
  "note": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "dateReferral": $.PropertyDesc<_cal.$local_date, $.Cardinality.AtMostOne, false, false, false, false>;
  "codeMultiCerts": $.LinkDesc<_sys_core.$Code, $.Cardinality.Many, {}, false, false,  false, false>;
  "<csfCohort[is app_cm_training::CsfCohortAttd]": $.LinkDesc<$CsfCohortAttd, $.Cardinality.Many, {}, false, false,  false, false>;
  "<csfCohort": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $CsfCohort = $.ObjectType<"app_cm_training::CsfCohort", $CsfCohortλShape, null, [
  ..._app_cm.$CsfData['__exclusives__'],
]>;
const $CsfCohort = $.makeType<$CsfCohort>(_.spec, "66168384-8faa-11ee-98ae-290ecec76018", _.syntax.literal);

const CsfCohort: $.$expr_PathNode<$.TypeSet<$CsfCohort, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CsfCohort, $.Cardinality.Many), null);

export type $CsfCohortAttdλShape = $.typeutil.flatten<_sys_user.$MgmtλShape & {
  "date": $.PropertyDesc<_cal.$local_date, $.Cardinality.One, false, false, false, false>;
  "note": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "csfCohort": $.LinkDesc<$CsfCohort, $.Cardinality.One, {}, false, false,  false, false>;
  "duration": $.PropertyDesc<_std.$float32, $.Cardinality.One, false, false, false, false>;
}>;
type $CsfCohortAttd = $.ObjectType<"app_cm_training::CsfCohortAttd", $CsfCohortAttdλShape, null, [
  ..._sys_user.$Mgmt['__exclusives__'],
]>;
const $CsfCohortAttd = $.makeType<$CsfCohortAttd>(_.spec, "661b166b-8faa-11ee-bf27-37fc298d68b5", _.syntax.literal);

const CsfCohortAttd: $.$expr_PathNode<$.TypeSet<$CsfCohortAttd, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CsfCohortAttd, $.Cardinality.Many), null);

type getCMTrainingCourseλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $Course, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getCMTrainingCourse<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  name: P1,
): getCMTrainingCourseλFuncExpr<P1>;
function getCMTrainingCourse(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('app_cm_training::getCMTrainingCourse', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "edb845d2-7d84-11ee-a1b3-051822eac25d", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "app_cm_training::getCMTrainingCourse",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};



export { $Cohort, Cohort, $Course, Course, $CsfCohort, CsfCohort, $CsfCohortAttd, CsfCohortAttd };

type __defaultExports = {
  "Cohort": typeof Cohort;
  "Course": typeof Course;
  "CsfCohort": typeof CsfCohort;
  "CsfCohortAttd": typeof CsfCohortAttd;
  "getCMTrainingCourse": typeof getCMTrainingCourse
};
const __defaultExports: __defaultExports = {
  "Cohort": Cohort,
  "Course": Course,
  "CsfCohort": CsfCohort,
  "CsfCohortAttd": CsfCohortAttd,
  "getCMTrainingCourse": getCMTrainingCourse
};
export default __defaultExports;
