// GENERATED by @edgedb/generate v0.4.1

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _sys_user from "./sys_user";
import type * as _sys_core from "./sys_core";
import type * as _default from "./default";
import type * as _std from "./std";
import type * as _cal from "./cal";
import type * as _app_cm_training from "./app_cm_training";
export type $ClientλShape = $.typeutil.flatten<_sys_user.$MgmtλShape & {
  "owner": $.LinkDesc<_sys_core.$Org, $.Cardinality.One, {}, false, false,  false, false>;
  "person": $.LinkDesc<_default.$Person, $.Cardinality.One, {}, false, false,  false, false>;
  "agencyId": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "<client[is app_cm::ClientServiceFlow]": $.LinkDesc<$ClientServiceFlow, $.Cardinality.Many, {}, false, false,  false, false>;
  "<client": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Client = $.ObjectType<"app_cm::Client", $ClientλShape, null, [
  ..._sys_user.$Mgmt['__exclusives__'],
]>;
const $Client = $.makeType<$Client>(_.spec, "f579cecf-8229-11ee-9f43-ab5bce31b5c4", _.syntax.literal);

const Client: $.$expr_PathNode<$.TypeSet<$Client, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Client, $.Cardinality.Many), null);

export type $ClientServiceFlowλShape = $.typeutil.flatten<_sys_user.$MgmtλShape & {
  "client": $.LinkDesc<$Client, $.Cardinality.One, {}, false, false,  false, false>;
  "codeStatus": $.LinkDesc<_sys_core.$Code, $.Cardinality.One, {}, false, false,  false, false>;
  "serviceFlow": $.LinkDesc<$ServiceFlow, $.Cardinality.One, {}, false, false,  false, false>;
  "dateEnd": $.PropertyDesc<_cal.$local_date, $.Cardinality.AtMostOne, false, false, false, false>;
  "dateEndEst": $.PropertyDesc<_cal.$local_date, $.Cardinality.AtMostOne, false, false, false, false>;
  "dateReferral": $.PropertyDesc<_cal.$local_date, $.Cardinality.One, false, false, false, false>;
  "dateStart": $.PropertyDesc<_cal.$local_date, $.Cardinality.AtMostOne, false, false, false, false>;
  "dateStartEst": $.PropertyDesc<_cal.$local_date, $.Cardinality.AtMostOne, false, false, false, false>;
  "note": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "<clientServiceFlow[is app_cm_training::CsfCohort]": $.LinkDesc<_app_cm_training.$CsfCohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<clientServiceFlow[is app_cm::CsfData]": $.LinkDesc<$CsfData, $.Cardinality.Many, {}, false, false,  false, false>;
  "<clientServiceFlow[is app_cm::CsfNote]": $.LinkDesc<$CsfNote, $.Cardinality.Many, {}, false, false,  false, false>;
  "<clientServiceFlow": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $ClientServiceFlow = $.ObjectType<"app_cm::ClientServiceFlow", $ClientServiceFlowλShape, null, [
  ..._sys_user.$Mgmt['__exclusives__'],
]>;
const $ClientServiceFlow = $.makeType<$ClientServiceFlow>(_.spec, "88d7af55-8fa8-11ee-8a55-9d463fc8b30b", _.syntax.literal);

const ClientServiceFlow: $.$expr_PathNode<$.TypeSet<$ClientServiceFlow, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($ClientServiceFlow, $.Cardinality.Many), null);

export type $CsfDataλShape = $.typeutil.flatten<_sys_user.$MgmtλShape & {
  "clientServiceFlow": $.LinkDesc<$ClientServiceFlow, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $CsfData = $.ObjectType<"app_cm::CsfData", $CsfDataλShape, null, [
  ..._sys_user.$Mgmt['__exclusives__'],
]>;
const $CsfData = $.makeType<$CsfData>(_.spec, "edaddbf1-8fa9-11ee-839f-1724c29a417c", _.syntax.literal);

const CsfData: $.$expr_PathNode<$.TypeSet<$CsfData, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CsfData, $.Cardinality.Many), null);

export type $CsfNoteλShape = $.typeutil.flatten<$CsfDataλShape & {
  "date": $.PropertyDesc<_cal.$local_date, $.Cardinality.One, false, false, false, false>;
  "note": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "codeType": $.LinkDesc<_sys_core.$Code, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $CsfNote = $.ObjectType<"app_cm::CsfNote", $CsfNoteλShape, null, [
  ...$CsfData['__exclusives__'],
]>;
const $CsfNote = $.makeType<$CsfNote>(_.spec, "edb10ba8-8fa9-11ee-9475-6dd31b7bdc06", _.syntax.literal);

const CsfNote: $.$expr_PathNode<$.TypeSet<$CsfNote, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CsfNote, $.Cardinality.Many), null);

export type $ServiceFlowλShape = $.typeutil.flatten<_sys_core.$ObjλShape & {
  "<serviceFlow[is app_cm::ClientServiceFlow]": $.LinkDesc<$ClientServiceFlow, $.Cardinality.Many, {}, false, false,  false, false>;
  "<serviceFlow": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $ServiceFlow = $.ObjectType<"app_cm::ServiceFlow", $ServiceFlowλShape, null, [
  ..._sys_core.$Obj['__exclusives__'],
]>;
const $ServiceFlow = $.makeType<$ServiceFlow>(_.spec, "88d4213f-8fa8-11ee-80a9-57c219054d1c", _.syntax.literal);

const ServiceFlow: $.$expr_PathNode<$.TypeSet<$ServiceFlow, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($ServiceFlow, $.Cardinality.Many), null);



export { $Client, Client, $ClientServiceFlow, ClientServiceFlow, $CsfData, CsfData, $CsfNote, CsfNote, $ServiceFlow, ServiceFlow };

type __defaultExports = {
  "Client": typeof Client;
  "ClientServiceFlow": typeof ClientServiceFlow;
  "CsfData": typeof CsfData;
  "CsfNote": typeof CsfNote;
  "ServiceFlow": typeof ServiceFlow
};
const __defaultExports: __defaultExports = {
  "Client": Client,
  "ClientServiceFlow": ClientServiceFlow,
  "CsfData": CsfData,
  "CsfNote": CsfNote,
  "ServiceFlow": ServiceFlow
};
export default __defaultExports;
