// GENERATED by @edgedb/generate v0.4.1

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _sys_core from "./sys_core";
import type * as _std from "./std";
export type $SaObjConfigλShape = $.typeutil.flatten<_sys_core.$SysObjλShape & {
  "creator": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailActions": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailDataObj": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailHeader": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailOrder": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailParentNodeName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailSubHeader": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "hasMgmt": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "icon": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "linkProperty": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "linkTableModule": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "linkTableName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listActions": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listDataObj": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listExprFilter": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listHeader": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listOrder": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne, false, false, false, false>;
  "listParentNodeName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listSubHeader": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "objsOwner": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "outputDetailColumns": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "outputDetailDataObj": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "outputDetailNode": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "outputListColumns": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "outputListDataObj": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "outputListNode": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "tableModule": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "tableName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "tableOwner": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $SaObjConfig = $.ObjectType<"sys_admin::SaObjConfig", $SaObjConfigλShape, null, [
  ..._sys_core.$SysObj['__exclusives__'],
]>;
const $SaObjConfig = $.makeType<$SaObjConfig>(_.spec, "a9529d7a-b15a-11ee-9d24-c7ff23b51ae8", _.syntax.literal);

const SaObjConfig: $.$expr_PathNode<$.TypeSet<$SaObjConfig, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SaObjConfig, $.Cardinality.Many), null);



export { $SaObjConfig, SaObjConfig };

type __defaultExports = {
  "SaObjConfig": typeof SaObjConfig
};
const __defaultExports: __defaultExports = {
  "SaObjConfig": SaObjConfig
};
export default __defaultExports;
