// GENERATED by @edgedb/generate v0.4.1

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _sys_core from "./sys_core";
import type * as _sys_db from "./sys_db";
import type * as _std from "./std";
import type * as _default from "./default";
export type $DataObjλShape = $.typeutil.flatten<_sys_core.$ObjλShape & {
  "codeCardinality": $.LinkDesc<_sys_core.$Code, $.Cardinality.One, {}, false, false,  false, false>;
  "codeComponent": $.LinkDesc<_sys_core.$Code, $.Cardinality.One, {}, false, false,  false, false>;
  "table": $.LinkDesc<_sys_db.$Table, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "exprFilter": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "exprObject": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "isPopup": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "link": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "subHeader": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "actions": $.LinkDesc<$DataObjAction, $.Cardinality.Many, {}, false, false,  false, false>;
  "fieldsDb": $.LinkDesc<$DataObjFieldDb, $.Cardinality.Many, {}, false, false,  false, false>;
  "fieldsEl": $.LinkDesc<$DataObjFieldEl, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dataObj[is sys_obj::NodeObj]": $.LinkDesc<$NodeObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dataObj[is sys_obj::NodeObjFooter]": $.LinkDesc<$NodeObjFooter, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dataObj": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $DataObj = $.ObjectType<"sys_obj::DataObj", $DataObjλShape, null, [
  ..._sys_core.$Obj['__exclusives__'],
]>;
const $DataObj = $.makeType<$DataObj>(_.spec, "c7694e8b-71ae-11ee-94f4-b7ed0524d481", _.syntax.literal);

const DataObj: $.$expr_PathNode<$.TypeSet<$DataObj, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($DataObj, $.Cardinality.Many), null);

export type $DataObjActionλShape = $.typeutil.flatten<_sys_core.$ObjλShape & {
  "color": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "order": $.PropertyDesc<_default.$nonNegative, $.Cardinality.One, false, false, false, false>;
  "allTabs": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "<actions[is sys_obj::DataObj]": $.LinkDesc<$DataObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<actions": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $DataObjAction = $.ObjectType<"sys_obj::DataObjAction", $DataObjActionλShape, null, [
  ..._sys_core.$Obj['__exclusives__'],
]>;
const $DataObjAction = $.makeType<$DataObjAction>(_.spec, "c76e660b-71ae-11ee-9c52-ef51abe79945", _.syntax.literal);

const DataObjAction: $.$expr_PathNode<$.TypeSet<$DataObjAction, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($DataObjAction, $.Cardinality.Many), null);

export type $DataObjFieldDbλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "codeDbDataOp": $.LinkDesc<_sys_core.$Code, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "codeDbDataSource": $.LinkDesc<_sys_core.$Code, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "codeDbListDir": $.LinkDesc<_sys_core.$Code, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "column": $.LinkDesc<_sys_db.$Column, $.Cardinality.One, {}, false, false,  false, false>;
  "dbDataSourceKey": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "dbOrderList": $.PropertyDesc<_default.$nonNegative, $.Cardinality.AtMostOne, false, false, false, false>;
  "exprFilter": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "exprPreset": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "fieldName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "isDbAllowNull": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "isDbFilter": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "isLinkMember": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "<fieldsDb[is sys_obj::DataObjFieldItems]": $.LinkDesc<$DataObjFieldItems, $.Cardinality.Many, {}, false, false,  false, false>;
  "<fieldsDb[is sys_obj::DataObj]": $.LinkDesc<$DataObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<fieldsDb": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $DataObjFieldDb = $.ObjectType<"sys_obj::DataObjFieldDb", $DataObjFieldDbλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $DataObjFieldDb = $.makeType<$DataObjFieldDb>(_.spec, "c7a7a524-71ae-11ee-900c-6b2d971bdd5a", _.syntax.literal);

const DataObjFieldDb: $.$expr_PathNode<$.TypeSet<$DataObjFieldDb, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($DataObjFieldDb, $.Cardinality.Many), null);

export type $DataObjFieldElλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "codeAccess": $.LinkDesc<_sys_core.$Code, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "codeElement": $.LinkDesc<_sys_core.$Code, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "column": $.LinkDesc<_sys_db.$Column, $.Cardinality.One, {}, false, false,  false, false>;
  "itemsList": $.LinkDesc<$DataObjFieldItems, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "dbOrderSelect": $.PropertyDesc<_default.$nonNegative, $.Cardinality.AtMostOne, false, false, false, false>;
  "headerAlt": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "height": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne, false, false, false, false>;
  "isDisplay": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "isDisplayable": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "items": $.PropertyDesc<$.ArrayType<_std.$json>, $.Cardinality.AtMostOne, false, false, false, false>;
  "itemsListParms": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "width": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne, false, false, false, false>;
  "dbOrderCrumb": $.PropertyDesc<_default.$nonNegative, $.Cardinality.AtMostOne, false, false, false, false>;
  "customElement": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "<fieldsEl[is sys_obj::DataObj]": $.LinkDesc<$DataObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<fieldsEl": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $DataObjFieldEl = $.ObjectType<"sys_obj::DataObjFieldEl", $DataObjFieldElλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $DataObjFieldEl = $.makeType<$DataObjFieldEl>(_.spec, "f2fba802-759e-11ee-a737-330989e7fe6c", _.syntax.literal);

const DataObjFieldEl: $.$expr_PathNode<$.TypeSet<$DataObjFieldEl, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($DataObjFieldEl, $.Cardinality.Many), null);

export type $DataObjFieldItemsλShape = $.typeutil.flatten<_sys_core.$ObjλShape & {
  "fieldsDb": $.LinkDesc<$DataObjFieldDb, $.Cardinality.Many, {}, false, false,  false, false>;
  "dbSelect": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "propertyId": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "propertyLabel": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<itemsList[is sys_obj::DataObjFieldEl]": $.LinkDesc<$DataObjFieldEl, $.Cardinality.Many, {}, false, false,  false, false>;
  "<itemsList": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $DataObjFieldItems = $.ObjectType<"sys_obj::DataObjFieldItems", $DataObjFieldItemsλShape, null, [
  ..._sys_core.$Obj['__exclusives__'],
]>;
const $DataObjFieldItems = $.makeType<$DataObjFieldItems>(_.spec, "8729f0d8-80f9-11ee-b72c-8d6ac69868d5", _.syntax.literal);

const DataObjFieldItems: $.$expr_PathNode<$.TypeSet<$DataObjFieldItems, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($DataObjFieldItems, $.Cardinality.Many), null);

export type $NodeObjλShape = $.typeutil.flatten<_sys_core.$ObjλShape & {
  "codeIcon": $.LinkDesc<_sys_core.$Code, $.Cardinality.One, {}, false, false,  false, false>;
  "codeType": $.LinkDesc<_sys_core.$Code, $.Cardinality.One, {}, false, false,  false, false>;
  "dataObj": $.LinkDesc<$DataObj, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "parent": $.LinkDesc<$NodeObj, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "order": $.PropertyDesc<_default.$nonNegative, $.Cardinality.One, false, false, false, false>;
  "page": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "queryActions": $.PropertyDesc<$.ArrayType<_std.$json>, $.Cardinality.AtMostOne, false, false, false, false>;
  "<parent[is sys_obj::NodeObj]": $.LinkDesc<$NodeObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent[is sys_obj::NodeObjFooter]": $.LinkDesc<$NodeObjFooter, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $NodeObj = $.ObjectType<"sys_obj::NodeObj", $NodeObjλShape, null, [
  ..._sys_core.$Obj['__exclusives__'],
]>;
const $NodeObj = $.makeType<$NodeObj>(_.spec, "c772cba6-71ae-11ee-887e-ad6bab7f4657", _.syntax.literal);

const NodeObj: $.$expr_PathNode<$.TypeSet<$NodeObj, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($NodeObj, $.Cardinality.Many), null);

export type $NodeObjFooterλShape = $.typeutil.flatten<$NodeObjλShape & {
}>;
type $NodeObjFooter = $.ObjectType<"sys_obj::NodeObjFooter", $NodeObjFooterλShape, null, [
  ...$NodeObj['__exclusives__'],
]>;
const $NodeObjFooter = $.makeType<$NodeObjFooter>(_.spec, "5833eb25-a972-11ee-8802-2fa91f7e22d5", _.syntax.literal);

const NodeObjFooter: $.$expr_PathNode<$.TypeSet<$NodeObjFooter, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($NodeObjFooter, $.Cardinality.Many), null);

type getDataObjλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $DataObj, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getDataObj<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  dataObjName: P1,
): getDataObjλFuncExpr<P1>;
function getDataObj(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_obj::getDataObj', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "c7694e8b-71ae-11ee-94f4-b7ed0524d481", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_obj::getDataObj",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getDataObjActionλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $DataObjAction, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getDataObjAction<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  dataObjActionName: P1,
): getDataObjActionλFuncExpr<P1>;
function getDataObjAction(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_obj::getDataObjAction', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "c76e660b-71ae-11ee-9c52-ef51abe79945", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_obj::getDataObjAction",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getNodeObjByIdλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $NodeObj, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getNodeObjById<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  nodeObjId: P1,
): getNodeObjByIdλFuncExpr<P1>;
function getNodeObjById(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_obj::getNodeObjById', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "c772cba6-71ae-11ee-887e-ad6bab7f4657", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_obj::getNodeObjById",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getNodeObjByNameλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $NodeObj, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getNodeObjByName<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  nodeObjName: P1,
): getNodeObjByNameλFuncExpr<P1>;
function getNodeObjByName(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_obj::getNodeObjByName', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "c772cba6-71ae-11ee-887e-ad6bab7f4657", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_obj::getNodeObjByName",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getDataObjFieldItemsλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $DataObjFieldItems, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getDataObjFieldItems<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  name: P1,
): getDataObjFieldItemsλFuncExpr<P1>;
function getDataObjFieldItems(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_obj::getDataObjFieldItems', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "8729f0d8-80f9-11ee-b72c-8d6ac69868d5", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_obj::getDataObjFieldItems",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};



export { $DataObj, DataObj, $DataObjAction, DataObjAction, $DataObjFieldDb, DataObjFieldDb, $DataObjFieldEl, DataObjFieldEl, $DataObjFieldItems, DataObjFieldItems, $NodeObj, NodeObj, $NodeObjFooter, NodeObjFooter };

type __defaultExports = {
  "DataObj": typeof DataObj;
  "DataObjAction": typeof DataObjAction;
  "DataObjFieldDb": typeof DataObjFieldDb;
  "DataObjFieldEl": typeof DataObjFieldEl;
  "DataObjFieldItems": typeof DataObjFieldItems;
  "NodeObj": typeof NodeObj;
  "NodeObjFooter": typeof NodeObjFooter;
  "getDataObj": typeof getDataObj;
  "getDataObjAction": typeof getDataObjAction;
  "getNodeObjById": typeof getNodeObjById;
  "getNodeObjByName": typeof getNodeObjByName;
  "getDataObjFieldItems": typeof getDataObjFieldItems
};
const __defaultExports: __defaultExports = {
  "DataObj": DataObj,
  "DataObjAction": DataObjAction,
  "DataObjFieldDb": DataObjFieldDb,
  "DataObjFieldEl": DataObjFieldEl,
  "DataObjFieldItems": DataObjFieldItems,
  "NodeObj": NodeObj,
  "NodeObjFooter": NodeObjFooter,
  "getDataObj": getDataObj,
  "getDataObjAction": getDataObjAction,
  "getNodeObjById": getNodeObjById,
  "getNodeObjByName": getNodeObjByName,
  "getDataObjFieldItems": getDataObjFieldItems
};
export default __defaultExports;
