// GENERATED by @edgedb/generate v0.4.1

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _app_cm from "./app_cm";
import type * as _sys_db from "./sys_db";
import type * as _sys_user from "./sys_user";
import type * as _default from "./default";
export type $ObjRootλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "header": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<owner[is sys_core::SysObj]": $.LinkDesc<$SysObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysCode]": $.LinkDesc<$SysCode, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysCodeType]": $.LinkDesc<$SysCodeType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysDataObj]": $.LinkDesc<$SysDataObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysDataObjAction]": $.LinkDesc<$SysDataObjAction, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysEnt]": $.LinkDesc<$SysEnt, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysNodeObj]": $.LinkDesc<$SysNodeObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysOrg]": $.LinkDesc<$SysOrg, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_db::SysColumn]": $.LinkDesc<_sys_db.$SysColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_db::SysTable]": $.LinkDesc<_sys_db.$SysTable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_user::SysUserType]": $.LinkDesc<_sys_user.$SysUserType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_user::SysWidget]": $.LinkDesc<_sys_user.$SysWidget, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is app_cm::CmServiceFlow]": $.LinkDesc<_app_cm.$CmServiceFlow, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is app_cm::CmCohort]": $.LinkDesc<_app_cm.$CmCohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysApp]": $.LinkDesc<$SysApp, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysNodeObjFooter]": $.LinkDesc<$SysNodeObjFooter, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysObjConfig]": $.LinkDesc<$SysObjConfig, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysDataObjFieldListItems]": $.LinkDesc<$SysDataObjFieldListItems, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is app_cm::CmEmployer]": $.LinkDesc<_app_cm.$CmEmployer, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysDataObjFieldListSelect]": $.LinkDesc<$SysDataObjFieldListSelect, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysDataObjFieldListConfig]": $.LinkDesc<$SysDataObjFieldListConfig, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_core::SysDataObjActionGroup]": $.LinkDesc<$SysDataObjActionGroup, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $ObjRoot = $.ObjectType<"sys_core::ObjRoot", $ObjRootλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $ObjRoot = $.makeType<$ObjRoot>(_.spec, "50288c7e-b3c2-11ee-9558-af251a93873c", _.syntax.literal);

const ObjRoot: $.$expr_PathNode<$.TypeSet<$ObjRoot, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($ObjRoot, $.Cardinality.Many), null);

export type $SysObjλShape = $.typeutil.flatten<$ObjRootλShape & _sys_user.$MgmtλShape & {
  "owner": $.LinkDesc<$ObjRoot, $.Cardinality.One, {}, false, false,  false, false>;
  "<resources[is sys_user::SysUserType]": $.LinkDesc<_sys_user.$SysUserType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<resources": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysObj = $.ObjectType<"sys_core::SysObj", $SysObjλShape, null, [
  ...$ObjRoot['__exclusives__'],
  ..._sys_user.$Mgmt['__exclusives__'],
]>;
const $SysObj = $.makeType<$SysObj>(_.spec, "502c3231-b3c2-11ee-8bbb-0d7244bf9fbc", _.syntax.literal);

const SysObj: $.$expr_PathNode<$.TypeSet<$SysObj, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysObj, $.Cardinality.Many), null);

export type $SysEntλShape = $.typeutil.flatten<$SysObjλShape & {
  "roles": $.LinkDesc<$SysCode, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysEnt = $.ObjectType<"sys_core::SysEnt", $SysEntλShape, null, [
  ...$SysObj['__exclusives__'],
]>;
const $SysEnt = $.makeType<$SysEnt>(_.spec, "5046e8f6-b3c2-11ee-9163-43cf7539562b", _.syntax.literal);

const SysEnt: $.$expr_PathNode<$.TypeSet<$SysEnt, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysEnt, $.Cardinality.Many), null);

export type $SysOrgλShape = $.typeutil.flatten<$SysEntλShape & {
  "addr1": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "addr2": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "city": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "zip": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "codeState": $.LinkDesc<$SysCode, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "<provider[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_user::SysStaff]": $.LinkDesc<_sys_user.$SysStaff, $.Cardinality.Many, {}, false, false,  false, false>;
  "<orgs[is sys_user::SysUser]": $.LinkDesc<_sys_user.$SysUser, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_user::SysUser]": $.LinkDesc<_sys_user.$SysUser, $.Cardinality.Many, {}, false, false,  false, false>;
  "<orgs[is sys_user::SYS_USER]": $.LinkDesc<_sys_user.$SYS_USER, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_user::SYS_USER]": $.LinkDesc<_sys_user.$SYS_USER, $.Cardinality.Many, {}, false, false,  false, false>;
  "<orgs[is sys_user::SYS_USER_ID]": $.LinkDesc<_sys_user.$SYS_USER_ID, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_user::SYS_USER_ID]": $.LinkDesc<_sys_user.$SYS_USER_ID, $.Cardinality.Many, {}, false, false,  false, false>;
  "<orgs[is sys_user::currentUser]": $.LinkDesc<_sys_user.$currentUser, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is sys_user::currentUser]": $.LinkDesc<_sys_user.$currentUser, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner[is app_cm::CmClient]": $.LinkDesc<_app_cm.$CmClient, $.Cardinality.Many, {}, false, false,  false, false>;
  "<venue[is app_cm::CmCohort]": $.LinkDesc<_app_cm.$CmCohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<orgs": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<owner": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<provider": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<venue": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysOrg = $.ObjectType<"sys_core::SysOrg", $SysOrgλShape, null, [
  ...$SysEnt['__exclusives__'],
]>;
const $SysOrg = $.makeType<$SysOrg>(_.spec, "504fffbe-b3c2-11ee-b5d1-fba024f44f35", _.syntax.literal);

const SysOrg: $.$expr_PathNode<$.TypeSet<$SysOrg, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysOrg, $.Cardinality.Many), null);

export type $SysAppλShape = $.typeutil.flatten<$SysEntλShape & {
}>;
type $SysApp = $.ObjectType<"sys_core::SysApp", $SysAppλShape, null, [
  ...$SysEnt['__exclusives__'],
]>;
const $SysApp = $.makeType<$SysApp>(_.spec, "50b0640c-b3c2-11ee-9af7-239681ad09d4", _.syntax.literal);

const SysApp: $.$expr_PathNode<$.TypeSet<$SysApp, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysApp, $.Cardinality.Many), null);

export type $SysCodeλShape = $.typeutil.flatten<$SysObjλShape & {
  "parent": $.LinkDesc<$SysCode, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "order": $.PropertyDesc<_default.$nonNegative, $.Cardinality.One, false, false, false, false>;
  "valueInteger": $.PropertyDesc<_std.$int64, $.Cardinality.AtMostOne, false, false, false, false>;
  "valueString": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "codeType": $.LinkDesc<$SysCodeType, $.Cardinality.One, {}, false, false,  false, false>;
  "valueDecimal": $.PropertyDesc<_std.$float64, $.Cardinality.AtMostOne, false, false, false, false>;
  "<codeSector[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeStatus[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent[is sys_core::SysCode]": $.LinkDesc<$SysCode, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeCardinality[is sys_core::SysDataObj]": $.LinkDesc<$SysDataObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeComponent[is sys_core::SysDataObj]": $.LinkDesc<$SysDataObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<roles[is sys_core::SysEnt]": $.LinkDesc<$SysEnt, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeIcon[is sys_core::SysNodeObj]": $.LinkDesc<$SysNodeObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeType[is sys_core::SysNodeObj]": $.LinkDesc<$SysNodeObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<roles[is sys_core::SysOrg]": $.LinkDesc<$SysOrg, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeAlignment[is sys_db::SysColumn]": $.LinkDesc<_sys_db.$SysColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDataType[is sys_db::SysColumn]": $.LinkDesc<_sys_db.$SysColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeEthnicity[is SysPerson]": $.LinkDesc<_default.$SysPerson, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeGender[is SysPerson]": $.LinkDesc<_default.$SysPerson, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeRace[is SysPerson]": $.LinkDesc<_default.$SysPerson, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeState[is SysPerson]": $.LinkDesc<_default.$SysPerson, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeState[is sys_core::SysOrg]": $.LinkDesc<$SysOrg, $.Cardinality.Many, {}, false, false,  false, false>;
  "<roles[is sys_user::SysStaff]": $.LinkDesc<_sys_user.$SysStaff, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeMultiRqmts[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeStatus[is app_cm::CmCohort]": $.LinkDesc<_app_cm.$CmCohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeStatus[is app_cm::CmCsfCohort]": $.LinkDesc<_app_cm.$CmCsfCohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeType[is app_cm::CmCsfNote]": $.LinkDesc<_app_cm.$CmCsfNote, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeMultiCerts[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeMultiExams[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeMultiItemsIncluded[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeMultiItemsNotIncluded[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<roles[is sys_core::SysApp]": $.LinkDesc<$SysApp, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeType[is sys_core::SysNodeObjFooter]": $.LinkDesc<$SysNodeObjFooter, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeIcon[is sys_core::SysNodeObjFooter]": $.LinkDesc<$SysNodeObjFooter, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDataTypeDisplay[is sys_core::SysDataObjFieldListItems]": $.LinkDesc<$SysDataObjFieldListItems, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeMask[is sys_core::SysDataObjFieldListItems]": $.LinkDesc<$SysDataObjFieldListItems, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDisplayDataType[is sys_core::SysDataObjFieldLink]": $.LinkDesc<$SysDataObjFieldLink, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDisplayMask[is sys_core::SysDataObjFieldLink]": $.LinkDesc<$SysDataObjFieldLink, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeAccess[is sys_core::SysDataObjColumn]": $.LinkDesc<$SysDataObjColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDbDataOp[is sys_core::SysDataObjColumn]": $.LinkDesc<$SysDataObjColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDbDataSource[is sys_core::SysDataObjColumn]": $.LinkDesc<$SysDataObjColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDbListDir[is sys_core::SysDataObjColumn]": $.LinkDesc<$SysDataObjColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeElement[is sys_core::SysDataObjColumn]": $.LinkDesc<$SysDataObjColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeJobType[is app_cm::CmCsfJobPlacement]": $.LinkDesc<_app_cm.$CmCsfJobPlacement, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codePlacementRelated[is app_cm::CmCsfJobPlacement]": $.LinkDesc<_app_cm.$CmCsfJobPlacement, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeWageType[is app_cm::CmCsfJobPlacement]": $.LinkDesc<_app_cm.$CmCsfJobPlacement, $.Cardinality.Many, {}, false, false,  false, false>;
  "<roles[is app_cm::CmEmployer]": $.LinkDesc<_app_cm.$CmEmployer, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeState[is app_cm::CmEmployer]": $.LinkDesc<_app_cm.$CmEmployer, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeType[is app_cm::CmCsfDocument]": $.LinkDesc<_app_cm.$CmCsfDocument, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeReferralEndType[is app_cm::CmClientServiceFlow]": $.LinkDesc<_app_cm.$CmClientServiceFlow, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeReferralType[is app_cm::CmClientServiceFlow]": $.LinkDesc<_app_cm.$CmClientServiceFlow, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeActionType[is sys_core::SysDataObjAction]": $.LinkDesc<$SysDataObjAction, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeRenderShowSaveMode[is sys_core::SysDataObjAction]": $.LinkDesc<$SysDataObjAction, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeCmCohortAttdDuration[is app_cm::CmCsfCohortAttd]": $.LinkDesc<_app_cm.$CmCsfCohortAttd, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeAccess": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeActionType": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeAlignment": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeCardinality": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeCmCohortAttdDuration": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeComponent": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDataType": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDataTypeDisplay": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDbDataOp": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDbDataSource": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDbListDir": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDisplayDataType": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeDisplayMask": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeElement": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeEthnicity": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeGender": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeIcon": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeJobType": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeMask": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeMultiCerts": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeMultiExams": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeMultiItemsIncluded": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeMultiItemsNotIncluded": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeMultiRqmts": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codePlacementRelated": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeRace": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeReferralEndType": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeReferralType": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeRenderShowSaveMode": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeSector": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeState": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeStatus": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeType": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeWageType": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<roles": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysCode = $.ObjectType<"sys_core::SysCode", $SysCodeλShape, null, [
  ...$SysObj['__exclusives__'],
]>;
const $SysCode = $.makeType<$SysCode>(_.spec, "5031fd57-b3c2-11ee-bf92-2bc5197f3279", _.syntax.literal);

const SysCode: $.$expr_PathNode<$.TypeSet<$SysCode, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysCode, $.Cardinality.Many), null);

export type $SysCodeTypeλShape = $.typeutil.flatten<$SysObjλShape & {
  "parent": $.LinkDesc<$SysCodeType, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "order": $.PropertyDesc<_default.$nonNegative, $.Cardinality.One, false, false, false, false>;
  "<codeTypePayment[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent[is sys_core::SysCodeType]": $.LinkDesc<$SysCodeType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeType[is sys_core::SysCode]": $.LinkDesc<$SysCode, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeType": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<codeTypePayment": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysCodeType = $.ObjectType<"sys_core::SysCodeType", $SysCodeTypeλShape, null, [
  ...$SysObj['__exclusives__'],
]>;
const $SysCodeType = $.makeType<$SysCodeType>(_.spec, "50345248-b3c2-11ee-98a3-49a9083e7b26", _.syntax.literal);

const SysCodeType: $.$expr_PathNode<$.TypeSet<$SysCodeType, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysCodeType, $.Cardinality.Many), null);

export type $SysDataObjλShape = $.typeutil.flatten<$SysObjλShape & {
  "codeCardinality": $.LinkDesc<$SysCode, $.Cardinality.One, {}, false, false,  false, false>;
  "codeComponent": $.LinkDesc<$SysCode, $.Cardinality.One, {}, false, false,  false, false>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "exprFilter": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "exprObject": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "subHeader": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "columns": $.LinkDesc<$SysDataObjColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "actionsQuery": $.PropertyDesc<$.ArrayType<_std.$json>, $.Cardinality.AtMostOne, false, false, false, false>;
  "actionsFieldGroup": $.LinkDesc<$SysDataObjActionGroup, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "tables": $.LinkDesc<$SysDataObjTable, $.Cardinality.Many, {}, false, false,  false, false>;
  "parentColumn": $.LinkDesc<_sys_db.$SysColumn, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "parentTable": $.LinkDesc<_sys_db.$SysTable, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "exprOrder": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "<dataObj[is sys_core::SysNodeObj]": $.LinkDesc<$SysNodeObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dataObj[is sys_core::SysNodeObjFooter]": $.LinkDesc<$SysNodeObjFooter, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dataObjDisplay[is sys_core::SysDataObjFieldListSelect]": $.LinkDesc<$SysDataObjFieldListSelect, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dataObjConfig[is sys_core::SysDataObjFieldListConfig]": $.LinkDesc<$SysDataObjFieldListConfig, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dataObjDisplay[is sys_core::SysDataObjFieldListConfig]": $.LinkDesc<$SysDataObjFieldListConfig, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dataObjSelect[is sys_core::SysDataObjFieldListSelect]": $.LinkDesc<$SysDataObjFieldListSelect, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dataObj": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dataObjConfig": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dataObjDisplay": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<dataObjSelect": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysDataObj = $.ObjectType<"sys_core::SysDataObj", $SysDataObjλShape, null, [
  ...$SysObj['__exclusives__'],
]>;
const $SysDataObj = $.makeType<$SysDataObj>(_.spec, "503b00ed-b3c2-11ee-8d94-1fcc024030a1", _.syntax.literal);

const SysDataObj: $.$expr_PathNode<$.TypeSet<$SysDataObj, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysDataObj, $.Cardinality.Many), null);

export type $SysDataObjActionλShape = $.typeutil.flatten<$SysObjλShape & {
  "color": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "order": $.PropertyDesc<_default.$nonNegative, $.Cardinality.One, false, false, false, false>;
  "checkObjChanged": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "codeActionType": $.LinkDesc<$SysCode, $.Cardinality.One, {}, false, false,  false, false>;
  "confirm": $.LinkDesc<$SysDataObjActionConfirm, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "codeRenderShowSaveMode": $.LinkDesc<$SysCode, $.Cardinality.One, {}, false, false,  false, false>;
  "isRenderDisableOnInvalidToSave": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "isRenderShowRequiresObjHasChanged": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "<actions[is sys_core::SysDataObjActionGroup]": $.LinkDesc<$SysDataObjActionGroup, $.Cardinality.Many, {}, false, false,  false, false>;
  "<actions": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysDataObjAction = $.ObjectType<"sys_core::SysDataObjAction", $SysDataObjActionλShape, null, [
  ...$SysObj['__exclusives__'],
]>;
const $SysDataObjAction = $.makeType<$SysDataObjAction>(_.spec, "503f7d4d-b3c2-11ee-a062-d1dfb79cac24", _.syntax.literal);

const SysDataObjAction: $.$expr_PathNode<$.TypeSet<$SysDataObjAction, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysDataObjAction, $.Cardinality.Many), null);

export type $SysDataObjActionConfirmλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "confirmButtonLabel": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "confirmMessage": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "confirmTitle": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<confirm[is sys_core::SysDataObjAction]": $.LinkDesc<$SysDataObjAction, $.Cardinality.Many, {}, false, false,  false, false>;
  "<confirm": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysDataObjActionConfirm = $.ObjectType<"sys_core::SysDataObjActionConfirm", $SysDataObjActionConfirmλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $SysDataObjActionConfirm = $.makeType<$SysDataObjActionConfirm>(_.spec, "9f5bd1c5-dda2-11ee-a63c-19556e0de346", _.syntax.literal);

const SysDataObjActionConfirm: $.$expr_PathNode<$.TypeSet<$SysDataObjActionConfirm, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysDataObjActionConfirm, $.Cardinality.Many), null);

export type $SysDataObjActionGroupλShape = $.typeutil.flatten<$SysObjλShape & {
  "actions": $.LinkDesc<$SysDataObjAction, $.Cardinality.Many, {}, false, false,  false, false>;
  "<actionsFieldGroup[is sys_core::SysDataObj]": $.LinkDesc<$SysDataObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<actionsFieldGroup[is sys_core::SysDataObjFieldListConfig]": $.LinkDesc<$SysDataObjFieldListConfig, $.Cardinality.Many, {}, false, false,  false, false>;
  "<actionsFieldGroup[is sys_core::SysDataObjFieldListSelect]": $.LinkDesc<$SysDataObjFieldListSelect, $.Cardinality.Many, {}, false, false,  false, false>;
  "<actionsFieldGroup": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysDataObjActionGroup = $.ObjectType<"sys_core::SysDataObjActionGroup", $SysDataObjActionGroupλShape, null, [
  ...$SysObj['__exclusives__'],
]>;
const $SysDataObjActionGroup = $.makeType<$SysDataObjActionGroup>(_.spec, "3a739b83-dc9e-11ee-a933-01eb1a0c94a6", _.syntax.literal);

const SysDataObjActionGroup: $.$expr_PathNode<$.TypeSet<$SysDataObjActionGroup, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysDataObjActionGroup, $.Cardinality.Many), null);

export type $SysDataObjColumnλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "codeAccess": $.LinkDesc<$SysCode, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "codeDbDataOp": $.LinkDesc<$SysCode, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "codeDbDataSource": $.LinkDesc<$SysCode, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "codeDbListDir": $.LinkDesc<$SysCode, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "codeElement": $.LinkDesc<$SysCode, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "column": $.LinkDesc<_sys_db.$SysColumn, $.Cardinality.One, {}, false, false,  false, false>;
  "customElement": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "dbDataSourceKey": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "dbOrderCrumb": $.PropertyDesc<_default.$nonNegative, $.Cardinality.AtMostOne, false, false, false, false>;
  "dbOrderList": $.PropertyDesc<_default.$nonNegative, $.Cardinality.AtMostOne, false, false, false, false>;
  "dbOrderSelect": $.PropertyDesc<_default.$nonNegative, $.Cardinality.AtMostOne, false, false, false, false>;
  "exprPresetScalar": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "fieldName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "headerAlt": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "height": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne, false, false, false, false>;
  "indexTable": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "isDbAllowNull": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "isDbFilter": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "isDisplay": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "isDisplayable": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "items": $.PropertyDesc<$.ArrayType<_std.$json>, $.Cardinality.AtMostOne, false, false, false, false>;
  "link": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "width": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne, false, false, false, false>;
  "exprCustom": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "nameCustom": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "fieldListItems": $.LinkDesc<$SysDataObjFieldListItems, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "fieldListItemsParms": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "fieldListSelect": $.LinkDesc<$SysDataObjFieldListSelect, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "fieldListConfig": $.LinkDesc<$SysDataObjFieldListConfig, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "isDisplayBlock": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "exprOrder": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "<columns[is sys_core::SysDataObj]": $.LinkDesc<$SysDataObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<columns": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysDataObjColumn = $.ObjectType<"sys_core::SysDataObjColumn", $SysDataObjColumnλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $SysDataObjColumn = $.makeType<$SysDataObjColumn>(_.spec, "20c31a70-baf0-11ee-aeba-051c5d5ed964", _.syntax.literal);

const SysDataObjColumn: $.$expr_PathNode<$.TypeSet<$SysDataObjColumn, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysDataObjColumn, $.Cardinality.Many), null);

export type $SysDataObjFieldLinkλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "exprSelect": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "codeDisplayDataType": $.LinkDesc<$SysCode, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "codeDisplayMask": $.LinkDesc<$SysCode, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "exprPreset": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "exprSave": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "columnsDisplay": $.LinkDesc<_sys_db.$SysColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "joins": $.LinkDesc<$SysDataObjFieldLinkJoin, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysDataObjFieldLink = $.ObjectType<"sys_core::SysDataObjFieldLink", $SysDataObjFieldLinkλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $SysDataObjFieldLink = $.makeType<$SysDataObjFieldLink>(_.spec, "ef3b142c-b53c-11ee-b1f8-cb4f06cb6de6", _.syntax.literal);

const SysDataObjFieldLink: $.$expr_PathNode<$.TypeSet<$SysDataObjFieldLink, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysDataObjFieldLink, $.Cardinality.Many), null);

export type $SysDataObjFieldLinkJoinλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "column": $.LinkDesc<_sys_db.$SysColumn, $.Cardinality.One, {}, false, false,  false, false>;
  "order": $.PropertyDesc<_default.$nonNegative, $.Cardinality.One, false, false, false, false>;
  "table": $.LinkDesc<_sys_db.$SysTable, $.Cardinality.One, {}, false, false,  false, false>;
  "<joins[is sys_core::SysDataObjFieldLink]": $.LinkDesc<$SysDataObjFieldLink, $.Cardinality.Many, {}, false, false,  false, false>;
  "<joins": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysDataObjFieldLinkJoin = $.ObjectType<"sys_core::SysDataObjFieldLinkJoin", $SysDataObjFieldLinkJoinλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $SysDataObjFieldLinkJoin = $.makeType<$SysDataObjFieldLinkJoin>(_.spec, "ce655d7c-b7e3-11ee-9e77-a9d97ad0285b", _.syntax.literal);

const SysDataObjFieldLinkJoin: $.$expr_PathNode<$.TypeSet<$SysDataObjFieldLinkJoin, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysDataObjFieldLinkJoin, $.Cardinality.Many), null);

export type $SysDataObjFieldListConfigλShape = $.typeutil.flatten<$SysObjλShape & {
  "dataObjConfig": $.LinkDesc<$SysDataObj, $.Cardinality.One, {}, false, false,  false, false>;
  "dataObjDisplay": $.LinkDesc<$SysDataObj, $.Cardinality.One, {}, false, false,  false, false>;
  "isMultiSelect": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "actionsFieldGroup": $.LinkDesc<$SysDataObjActionGroup, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "<fieldListConfig[is sys_core::SysDataObjColumn]": $.LinkDesc<$SysDataObjColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "<fieldListConfig": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysDataObjFieldListConfig = $.ObjectType<"sys_core::SysDataObjFieldListConfig", $SysDataObjFieldListConfigλShape, null, [
  ...$SysObj['__exclusives__'],
]>;
const $SysDataObjFieldListConfig = $.makeType<$SysDataObjFieldListConfig>(_.spec, "212efe62-da46-11ee-b035-fd37f7fe64a5", _.syntax.literal);

const SysDataObjFieldListConfig: $.$expr_PathNode<$.TypeSet<$SysDataObjFieldListConfig, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysDataObjFieldListConfig, $.Cardinality.Many), null);

export type $SysDataObjFieldListItemsλShape = $.typeutil.flatten<$SysObjλShape & {
  "codeDataTypeDisplay": $.LinkDesc<$SysCode, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "codeMask": $.LinkDesc<$SysCode, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "exprSelect": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<fieldListItems[is sys_core::SysDataObjColumn]": $.LinkDesc<$SysDataObjColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "<fieldListItems": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysDataObjFieldListItems = $.ObjectType<"sys_core::SysDataObjFieldListItems", $SysDataObjFieldListItemsλShape, null, [
  ...$SysObj['__exclusives__'],
]>;
const $SysDataObjFieldListItems = $.makeType<$SysDataObjFieldListItems>(_.spec, "5043353f-b3c2-11ee-82a7-f9c2cda88f1f", _.syntax.literal);

const SysDataObjFieldListItems: $.$expr_PathNode<$.TypeSet<$SysDataObjFieldListItems, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysDataObjFieldListItems, $.Cardinality.Many), null);

export type $SysDataObjFieldListSelectλShape = $.typeutil.flatten<$SysObjλShape & {
  "btnLabelComplete": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "isMultiSelect": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "actionsFieldGroup": $.LinkDesc<$SysDataObjActionGroup, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "dataObjDisplay": $.LinkDesc<$SysDataObj, $.Cardinality.One, {}, false, false,  false, false>;
  "dataObjSelect": $.LinkDesc<$SysDataObj, $.Cardinality.One, {}, false, false,  false, false>;
  "<fieldListSelect[is sys_core::SysDataObjColumn]": $.LinkDesc<$SysDataObjColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "<fieldListSelect": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysDataObjFieldListSelect = $.ObjectType<"sys_core::SysDataObjFieldListSelect", $SysDataObjFieldListSelectλShape, null, [
  ...$SysObj['__exclusives__'],
]>;
const $SysDataObjFieldListSelect = $.makeType<$SysDataObjFieldListSelect>(_.spec, "5821d1df-d4e2-11ee-80e4-b9e048ba3471", _.syntax.literal);

const SysDataObjFieldListSelect: $.$expr_PathNode<$.TypeSet<$SysDataObjFieldListSelect, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysDataObjFieldListSelect, $.Cardinality.Many), null);

export type $SysDataObjTableλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "table": $.LinkDesc<_sys_db.$SysTable, $.Cardinality.One, {}, false, false,  false, false>;
  "index": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "indexParent": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "columnParent": $.LinkDesc<_sys_db.$SysColumn, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "order": $.PropertyDesc<_default.$nonNegative, $.Cardinality.One, false, false, false, false>;
  "<tables[is sys_core::SysDataObj]": $.LinkDesc<$SysDataObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tables": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysDataObjTable = $.ObjectType<"sys_core::SysDataObjTable", $SysDataObjTableλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $SysDataObjTable = $.makeType<$SysDataObjTable>(_.spec, "25add2b2-b895-11ee-8fc4-e5eb3e9588df", _.syntax.literal);

const SysDataObjTable: $.$expr_PathNode<$.TypeSet<$SysDataObjTable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysDataObjTable, $.Cardinality.Many), null);

export type $SysNodeObjλShape = $.typeutil.flatten<$SysObjλShape & {
  "codeIcon": $.LinkDesc<$SysCode, $.Cardinality.One, {}, false, false,  false, false>;
  "codeType": $.LinkDesc<$SysCode, $.Cardinality.One, {}, false, false,  false, false>;
  "dataObj": $.LinkDesc<$SysDataObj, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "parent": $.LinkDesc<$SysNodeObj, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "order": $.PropertyDesc<_default.$nonNegative, $.Cardinality.One, false, false, false, false>;
  "page": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "<parent[is sys_core::SysNodeObj]": $.LinkDesc<$SysNodeObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent[is sys_core::SysNodeObjFooter]": $.LinkDesc<$SysNodeObjFooter, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysNodeObj = $.ObjectType<"sys_core::SysNodeObj", $SysNodeObjλShape, null, [
  ...$SysObj['__exclusives__'],
]>;
const $SysNodeObj = $.makeType<$SysNodeObj>(_.spec, "504a9d6b-b3c2-11ee-b8ef-274055b9abd1", _.syntax.literal);

const SysNodeObj: $.$expr_PathNode<$.TypeSet<$SysNodeObj, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysNodeObj, $.Cardinality.Many), null);

export type $SysNodeObjFooterλShape = $.typeutil.flatten<$SysNodeObjλShape & {
}>;
type $SysNodeObjFooter = $.ObjectType<"sys_core::SysNodeObjFooter", $SysNodeObjFooterλShape, null, [
  ...$SysNodeObj['__exclusives__'],
]>;
const $SysNodeObjFooter = $.makeType<$SysNodeObjFooter>(_.spec, "50b3e130-b3c2-11ee-b0e5-e73c7524bd47", _.syntax.literal);

const SysNodeObjFooter: $.$expr_PathNode<$.TypeSet<$SysNodeObjFooter, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysNodeObjFooter, $.Cardinality.Many), null);

export type $SysObjConfigλShape = $.typeutil.flatten<$SysObjλShape & {
  "creator": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailActions": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailDataObj": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailHeader": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailOrder": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailParentNodeName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "detailSubHeader": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "hasMgmt": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "icon": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "linkProperty": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "linkTableModule": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "linkTableName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listActions": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listDataObj": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listExprFilter": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listHeader": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listOrder": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne, false, false, false, false>;
  "listParentNodeName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "listSubHeader": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "objsOwner": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "outputDetailColumns": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "outputDetailDataObj": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "outputDetailNode": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "outputListColumns": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "outputListDataObj": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "outputListNode": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "tableModule": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "tableName": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "tableOwner": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $SysObjConfig = $.ObjectType<"sys_core::SysObjConfig", $SysObjConfigλShape, null, [
  ...$SysObj['__exclusives__'],
]>;
const $SysObjConfig = $.makeType<$SysObjConfig>(_.spec, "d3b786fd-baac-11ee-a3cc-d53e3f081808", _.syntax.literal);

const SysObjConfig: $.$expr_PathNode<$.TypeSet<$SysObjConfig, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysObjConfig, $.Cardinality.Many), null);

type getCodeλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
  P2 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysCode, $.cardutil.overrideLowerBound<$.cardutil.multiplyCardinalities<$.cardutil.paramCardinality<P1>, $.cardutil.paramCardinality<P2>>, 'Zero'>
>;
function getCode<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
  P2 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  codeTypeName: P1,
  codeName: P2,
): getCodeλFuncExpr<P1, P2>;
function getCode(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::getCode', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}, {typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "5031fd57-b3c2-11ee-bf92-2bc5197f3279", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::getCode",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getCodeTypeλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysCodeType, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getCodeType<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  codeTypeName: P1,
): getCodeTypeλFuncExpr<P1>;
function getCodeType(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::getCodeType', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "50345248-b3c2-11ee-98a3-49a9083e7b26", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::getCodeType",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getDataObjλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysDataObj, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getDataObj<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  dataObjName: P1,
): getDataObjλFuncExpr<P1>;
function getDataObj(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::getDataObj', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "503b00ed-b3c2-11ee-8d94-1fcc024030a1", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::getDataObj",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getDataObjActionλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysDataObjAction, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getDataObjAction<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  dataObjActionName: P1,
): getDataObjActionλFuncExpr<P1>;
function getDataObjAction(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::getDataObjAction', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "503f7d4d-b3c2-11ee-a062-d1dfb79cac24", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::getDataObjAction",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getEntλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysEnt, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getEnt<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  entName: P1,
): getEntλFuncExpr<P1>;
function getEnt(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::getEnt', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "5046e8f6-b3c2-11ee-9163-43cf7539562b", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::getEnt",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getNodeObjByIdλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysNodeObj, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getNodeObjById<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  nodeObjId: P1,
): getNodeObjByIdλFuncExpr<P1>;
function getNodeObjById(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::getNodeObjById', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "504a9d6b-b3c2-11ee-b8ef-274055b9abd1", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::getNodeObjById",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getNodeObjByNameλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysNodeObj, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getNodeObjByName<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  nodeObjName: P1,
): getNodeObjByNameλFuncExpr<P1>;
function getNodeObjByName(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::getNodeObjByName', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "504a9d6b-b3c2-11ee-b8ef-274055b9abd1", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::getNodeObjByName",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getOrgλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysOrg, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getOrg<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  name: P1,
): getOrgλFuncExpr<P1>;
function getOrg(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::getOrg', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "504fffbe-b3c2-11ee-b5d1-fba024f44f35", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::getOrg",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getRootObjλFuncExpr = $.$expr_Function<
  $ObjRoot, $.cardutil.overrideLowerBound<$.Cardinality.One, 'Zero'>
>;
function getRootObj(): getRootObjλFuncExpr;
function getRootObj(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::getRootObj', args, _.spec, [
    {args: [], returnTypeId: "50288c7e-b3c2-11ee-9558-af251a93873c", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::getRootObj",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type isObjectLinkλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
  P2 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  _std.$bool, $.cardutil.overrideLowerBound<$.cardutil.multiplyCardinalities<$.cardutil.paramCardinality<P1>, $.cardutil.paramCardinality<P2>>, 'Zero'>
>;
function isObjectLink<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
  P2 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  objName: P1,
  linkName: P2,
): isObjectLinkλFuncExpr<P1, P2>;
function isObjectLink(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::isObjectLink', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}, {typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "00000000-0000-0000-0000-000000000109", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::isObjectLink",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getDataObjFieldListSelectλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysDataObjFieldListSelect, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getDataObjFieldListSelect<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  name: P1,
): getDataObjFieldListSelectλFuncExpr<P1>;
function getDataObjFieldListSelect(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::getDataObjFieldListSelect', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "5821d1df-d4e2-11ee-80e4-b9e048ba3471", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::getDataObjFieldListSelect",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getDataObjFieldListConfigλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysDataObjFieldListConfig, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getDataObjFieldListConfig<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  name: P1,
): getDataObjFieldListConfigλFuncExpr<P1>;
function getDataObjFieldListConfig(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::getDataObjFieldListConfig', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "212efe62-da46-11ee-b035-fd37f7fe64a5", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::getDataObjFieldListConfig",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getDataObjFieldListItemsλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysDataObjFieldListItems, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getDataObjFieldListItems<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  name: P1,
): getDataObjFieldListItemsλFuncExpr<P1>;
function getDataObjFieldListItems(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::getDataObjFieldListItems', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "5043353f-b3c2-11ee-82a7-f9c2cda88f1f", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::getDataObjFieldListItems",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getDataObjActionGroupλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysDataObjActionGroup, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getDataObjActionGroup<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  name: P1,
): getDataObjActionGroupλFuncExpr<P1>;
function getDataObjActionGroup(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_core::getDataObjActionGroup', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "3a739b83-dc9e-11ee-a933-01eb1a0c94a6", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_core::getDataObjActionGroup",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};



export { $ObjRoot, ObjRoot, $SysObj, SysObj, $SysEnt, SysEnt, $SysOrg, SysOrg, $SysApp, SysApp, $SysCode, SysCode, $SysCodeType, SysCodeType, $SysDataObj, SysDataObj, $SysDataObjAction, SysDataObjAction, $SysDataObjActionConfirm, SysDataObjActionConfirm, $SysDataObjActionGroup, SysDataObjActionGroup, $SysDataObjColumn, SysDataObjColumn, $SysDataObjFieldLink, SysDataObjFieldLink, $SysDataObjFieldLinkJoin, SysDataObjFieldLinkJoin, $SysDataObjFieldListConfig, SysDataObjFieldListConfig, $SysDataObjFieldListItems, SysDataObjFieldListItems, $SysDataObjFieldListSelect, SysDataObjFieldListSelect, $SysDataObjTable, SysDataObjTable, $SysNodeObj, SysNodeObj, $SysNodeObjFooter, SysNodeObjFooter, $SysObjConfig, SysObjConfig };

type __defaultExports = {
  "ObjRoot": typeof ObjRoot;
  "SysObj": typeof SysObj;
  "SysEnt": typeof SysEnt;
  "SysOrg": typeof SysOrg;
  "SysApp": typeof SysApp;
  "SysCode": typeof SysCode;
  "SysCodeType": typeof SysCodeType;
  "SysDataObj": typeof SysDataObj;
  "SysDataObjAction": typeof SysDataObjAction;
  "SysDataObjActionConfirm": typeof SysDataObjActionConfirm;
  "SysDataObjActionGroup": typeof SysDataObjActionGroup;
  "SysDataObjColumn": typeof SysDataObjColumn;
  "SysDataObjFieldLink": typeof SysDataObjFieldLink;
  "SysDataObjFieldLinkJoin": typeof SysDataObjFieldLinkJoin;
  "SysDataObjFieldListConfig": typeof SysDataObjFieldListConfig;
  "SysDataObjFieldListItems": typeof SysDataObjFieldListItems;
  "SysDataObjFieldListSelect": typeof SysDataObjFieldListSelect;
  "SysDataObjTable": typeof SysDataObjTable;
  "SysNodeObj": typeof SysNodeObj;
  "SysNodeObjFooter": typeof SysNodeObjFooter;
  "SysObjConfig": typeof SysObjConfig;
  "getCode": typeof getCode;
  "getCodeType": typeof getCodeType;
  "getDataObj": typeof getDataObj;
  "getDataObjAction": typeof getDataObjAction;
  "getEnt": typeof getEnt;
  "getNodeObjById": typeof getNodeObjById;
  "getNodeObjByName": typeof getNodeObjByName;
  "getOrg": typeof getOrg;
  "getRootObj": typeof getRootObj;
  "isObjectLink": typeof isObjectLink;
  "getDataObjFieldListSelect": typeof getDataObjFieldListSelect;
  "getDataObjFieldListConfig": typeof getDataObjFieldListConfig;
  "getDataObjFieldListItems": typeof getDataObjFieldListItems;
  "getDataObjActionGroup": typeof getDataObjActionGroup
};
const __defaultExports: __defaultExports = {
  "ObjRoot": ObjRoot,
  "SysObj": SysObj,
  "SysEnt": SysEnt,
  "SysOrg": SysOrg,
  "SysApp": SysApp,
  "SysCode": SysCode,
  "SysCodeType": SysCodeType,
  "SysDataObj": SysDataObj,
  "SysDataObjAction": SysDataObjAction,
  "SysDataObjActionConfirm": SysDataObjActionConfirm,
  "SysDataObjActionGroup": SysDataObjActionGroup,
  "SysDataObjColumn": SysDataObjColumn,
  "SysDataObjFieldLink": SysDataObjFieldLink,
  "SysDataObjFieldLinkJoin": SysDataObjFieldLinkJoin,
  "SysDataObjFieldListConfig": SysDataObjFieldListConfig,
  "SysDataObjFieldListItems": SysDataObjFieldListItems,
  "SysDataObjFieldListSelect": SysDataObjFieldListSelect,
  "SysDataObjTable": SysDataObjTable,
  "SysNodeObj": SysNodeObj,
  "SysNodeObjFooter": SysNodeObjFooter,
  "SysObjConfig": SysObjConfig,
  "getCode": getCode,
  "getCodeType": getCodeType,
  "getDataObj": getDataObj,
  "getDataObjAction": getDataObjAction,
  "getEnt": getEnt,
  "getNodeObjById": getNodeObjById,
  "getNodeObjByName": getNodeObjByName,
  "getOrg": getOrg,
  "getRootObj": getRootObj,
  "isObjectLink": isObjectLink,
  "getDataObjFieldListSelect": getDataObjFieldListSelect,
  "getDataObjFieldListConfig": getDataObjFieldListConfig,
  "getDataObjFieldListItems": getDataObjFieldListItems,
  "getDataObjActionGroup": getDataObjActionGroup
};
export default __defaultExports;
