// GENERATED by @edgedb/generate v0.4.1

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _default from "./default";
import type * as _sys_core from "./sys_core";
import type * as _sys_db from "./sys_db";
import type * as _app_cm from "./app_cm";
export type $MgmtλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, true, true>;
  "modifiedAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "createdBy": $.LinkDesc<$UserRoot, $.Cardinality.One, {}, false, false,  true, false>;
  "modifiedBy": $.LinkDesc<$UserRoot, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $Mgmt = $.ObjectType<"sys_user::Mgmt", $MgmtλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Mgmt = $.makeType<$Mgmt>(_.spec, "5029d127-b3c2-11ee-a4fe-a73f30dac3e0", _.syntax.literal);

const Mgmt: $.$expr_PathNode<$.TypeSet<$Mgmt, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Mgmt, $.Cardinality.Many), null);

export type $UserRootλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "userName": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "person": $.LinkDesc<_default.$SysPerson, $.Cardinality.One, {}, false, false,  false, false>;
  "<createdBy[is sys_user::Mgmt]": $.LinkDesc<$Mgmt, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_core::SysObj]": $.LinkDesc<_sys_core.$SysObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_core::SysCode]": $.LinkDesc<_sys_core.$SysCode, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_core::SysDataObjFieldItemsDb]": $.LinkDesc<_sys_core.$SysDataObjFieldItemsDb, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_core::SysDataObj]": $.LinkDesc<_sys_core.$SysDataObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_db::SysTable]": $.LinkDesc<_sys_db.$SysTable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_core::SysDataObjAction]": $.LinkDesc<_sys_core.$SysDataObjAction, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_core::SysCodeType]": $.LinkDesc<_sys_core.$SysCodeType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_core::SysEnt]": $.LinkDesc<_sys_core.$SysEnt, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_core::SysOrg]": $.LinkDesc<_sys_core.$SysOrg, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_db::SysColumn]": $.LinkDesc<_sys_db.$SysColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_core::SysNodeObj]": $.LinkDesc<_sys_core.$SysNodeObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_user::Mgmt]": $.LinkDesc<$Mgmt, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_core::SysObj]": $.LinkDesc<_sys_core.$SysObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_core::SysCode]": $.LinkDesc<_sys_core.$SysCode, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_core::SysDataObjFieldItemsDb]": $.LinkDesc<_sys_core.$SysDataObjFieldItemsDb, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_core::SysDataObj]": $.LinkDesc<_sys_core.$SysDataObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_db::SysTable]": $.LinkDesc<_sys_db.$SysTable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_core::SysDataObjAction]": $.LinkDesc<_sys_core.$SysDataObjAction, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_core::SysCodeType]": $.LinkDesc<_sys_core.$SysCodeType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_core::SysEnt]": $.LinkDesc<_sys_core.$SysEnt, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_core::SysOrg]": $.LinkDesc<_sys_core.$SysOrg, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_db::SysColumn]": $.LinkDesc<_sys_db.$SysColumn, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_core::SysNodeObj]": $.LinkDesc<_sys_core.$SysNodeObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_user::SysStaff]": $.LinkDesc<$SysStaff, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_user::SysStaff]": $.LinkDesc<$SysStaff, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_user::SysUserType]": $.LinkDesc<$SysUserType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_user::SysUserType]": $.LinkDesc<$SysUserType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_user::SysUser]": $.LinkDesc<$SysUser, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_user::SysUser]": $.LinkDesc<$SysUser, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_user::SysWidget]": $.LinkDesc<$SysWidget, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_user::SysWidget]": $.LinkDesc<$SysWidget, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_user::SYS_USER]": $.LinkDesc<$SYS_USER, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_user::SYS_USER]": $.LinkDesc<$SYS_USER, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_user::SYS_USER_ID]": $.LinkDesc<$SYS_USER_ID, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_user::SYS_USER_ID]": $.LinkDesc<$SYS_USER_ID, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_user::currentUser]": $.LinkDesc<$currentUser, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_user::currentUser]": $.LinkDesc<$currentUser, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is app_cm::CmClient]": $.LinkDesc<_app_cm.$CmClient, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is app_cm::CmClient]": $.LinkDesc<_app_cm.$CmClient, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is app_cm::CmServiceFlow]": $.LinkDesc<_app_cm.$CmServiceFlow, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is app_cm::CmServiceFlow]": $.LinkDesc<_app_cm.$CmServiceFlow, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is app_cm::CmClientServiceFlow]": $.LinkDesc<_app_cm.$CmClientServiceFlow, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is app_cm::CmClientServiceFlow]": $.LinkDesc<_app_cm.$CmClientServiceFlow, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is app_cm::CmCsfData]": $.LinkDesc<_app_cm.$CmCsfData, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is app_cm::CmCsfData]": $.LinkDesc<_app_cm.$CmCsfData, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is app_cm::CmCsfCertification]": $.LinkDesc<_app_cm.$CmCsfCertification, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is app_cm::CmCsfCertification]": $.LinkDesc<_app_cm.$CmCsfCertification, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is app_cm::CmCohort]": $.LinkDesc<_app_cm.$CmCohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is app_cm::CmCohort]": $.LinkDesc<_app_cm.$CmCohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is app_cm::CmCsfCohort]": $.LinkDesc<_app_cm.$CmCsfCohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is app_cm::CmCsfCohort]": $.LinkDesc<_app_cm.$CmCsfCohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is app_cm::CmCsfNote]": $.LinkDesc<_app_cm.$CmCsfNote, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is app_cm::CmCsfNote]": $.LinkDesc<_app_cm.$CmCsfNote, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is app_cm::CmCsfCohortAttd]": $.LinkDesc<_app_cm.$CmCsfCohortAttd, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is app_cm::CmCsfCohortAttd]": $.LinkDesc<_app_cm.$CmCsfCohortAttd, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_core::SysApp]": $.LinkDesc<_sys_core.$SysApp, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_core::SysApp]": $.LinkDesc<_sys_core.$SysApp, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_core::SysNodeObjFooter]": $.LinkDesc<_sys_core.$SysNodeObjFooter, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_core::SysNodeObjFooter]": $.LinkDesc<_sys_core.$SysNodeObjFooter, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_core::SysObjConfig]": $.LinkDesc<_sys_core.$SysObjConfig, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_core::SysObjConfig]": $.LinkDesc<_sys_core.$SysObjConfig, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy[is sys_core::SysOverlayNode]": $.LinkDesc<_sys_core.$SysOverlayNode, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy[is sys_core::SysOverlayNode]": $.LinkDesc<_sys_core.$SysOverlayNode, $.Cardinality.Many, {}, false, false,  false, false>;
  "<createdBy": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<modifiedBy": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $UserRoot = $.ObjectType<"sys_user::UserRoot", $UserRootλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $UserRoot = $.makeType<$UserRoot>(_.spec, "505f29d6-b3c2-11ee-a534-b73af31574a8", _.syntax.literal);

const UserRoot: $.$expr_PathNode<$.TypeSet<$UserRoot, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($UserRoot, $.Cardinality.Many), null);

export type $SysUserλShape = $.typeutil.flatten<$UserRootλShape & $MgmtλShape & {
  "orgs": $.LinkDesc<_sys_core.$SysOrg, $.Cardinality.Many, {}, false, false,  false, false>;
  "owner": $.LinkDesc<_sys_core.$SysOrg, $.Cardinality.One, {}, false, false,  false, false>;
  "userTypes": $.LinkDesc<$SysUserType, $.Cardinality.Many, {}, false, false,  false, false>;
  "password": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $SysUser = $.ObjectType<"sys_user::SysUser", $SysUserλShape, null, [
  ...$UserRoot['__exclusives__'],
  ...$Mgmt['__exclusives__'],
]>;
const $SysUser = $.makeType<$SysUser>(_.spec, "50759917-b3c2-11ee-a6a5-635e27965552", _.syntax.literal);

const SysUser: $.$expr_PathNode<$.TypeSet<$SysUser, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysUser, $.Cardinality.Many), null);

export type $SYS_USERλShape = $.typeutil.flatten<$SysUserλShape & {
}>;
type $SYS_USER = $.ObjectType<"sys_user::SYS_USER", $SYS_USERλShape, null, [
  ...$SysUser['__exclusives__'],
]>;
const $SYS_USER = $.makeType<$SYS_USER>(_.spec, "50836d83-b3c2-11ee-8679-3b42549300f4", _.syntax.literal);

const SYS_USER: $.$expr_PathNode<$.TypeSet<$SYS_USER, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SYS_USER, $.Cardinality.Many), null);

export type $SYS_USER_IDλShape = $.typeutil.flatten<$SysUserλShape & {
}>;
type $SYS_USER_ID = $.ObjectType<"sys_user::SYS_USER_ID", $SYS_USER_IDλShape, null, [
  ...$SysUser['__exclusives__'],
]>;
const $SYS_USER_ID = $.makeType<$SYS_USER_ID>(_.spec, "50881349-b3c2-11ee-a2ed-1f5ea2f3a678", _.syntax.literal);

const SYS_USER_ID: $.$expr_PathNode<$.TypeSet<$SYS_USER_ID, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SYS_USER_ID, $.Cardinality.Many), null);

export type $SysStaffλShape = $.typeutil.flatten<$MgmtλShape & {
  "person": $.LinkDesc<_default.$SysPerson, $.Cardinality.One, {}, false, false,  false, false>;
  "roles": $.LinkDesc<_sys_core.$SysCode, $.Cardinality.Many, {}, false, false,  false, false>;
  "owner": $.LinkDesc<_sys_core.$SysOrg, $.Cardinality.One, {}, false, false,  false, false>;
  "<staffAgency[is app_cm::CmCsfCertification]": $.LinkDesc<_app_cm.$CmCsfCertification, $.Cardinality.Many, {}, false, false,  false, false>;
  "<staffAdmin[is app_cm::CmCohort]": $.LinkDesc<_app_cm.$CmCohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<staffAgency[is app_cm::CmCohort]": $.LinkDesc<_app_cm.$CmCohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<staffInstructor[is app_cm::CmCohort]": $.LinkDesc<_app_cm.$CmCohort, $.Cardinality.Many, {}, false, false,  false, false>;
  "<staffAdmin[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<staffAgency[is app_cm::CmCourse]": $.LinkDesc<_app_cm.$CmCourse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<staffAdmin": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<staffAgency": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<staffInstructor": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysStaff = $.ObjectType<"sys_user::SysStaff", $SysStaffλShape, null, [
  ...$Mgmt['__exclusives__'],
]>;
const $SysStaff = $.makeType<$SysStaff>(_.spec, "506d1594-b3c2-11ee-8a4e-7313d86159be", _.syntax.literal);

const SysStaff: $.$expr_PathNode<$.TypeSet<$SysStaff, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysStaff, $.Cardinality.Many), null);

export type $SysUserTypeλShape = $.typeutil.flatten<_sys_core.$SysObjλShape & {
  "resources": $.LinkDesc<_sys_core.$SysObj, $.Cardinality.Many, {}, false, false,  false, false>;
  "<userTypes[is sys_user::SysUser]": $.LinkDesc<$SysUser, $.Cardinality.Many, {}, false, false,  false, false>;
  "<userTypes[is sys_user::SYS_USER]": $.LinkDesc<$SYS_USER, $.Cardinality.Many, {}, false, false,  false, false>;
  "<userTypes[is sys_user::SYS_USER_ID]": $.LinkDesc<$SYS_USER_ID, $.Cardinality.Many, {}, false, false,  false, false>;
  "<userTypes[is sys_user::currentUser]": $.LinkDesc<$currentUser, $.Cardinality.Many, {}, false, false,  false, false>;
  "<userTypes": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SysUserType = $.ObjectType<"sys_user::SysUserType", $SysUserTypeλShape, null, [
  ..._sys_core.$SysObj['__exclusives__'],
]>;
const $SysUserType = $.makeType<$SysUserType>(_.spec, "5071c13e-b3c2-11ee-b22f-ff2605d1c34f", _.syntax.literal);

const SysUserType: $.$expr_PathNode<$.TypeSet<$SysUserType, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysUserType, $.Cardinality.Many), null);

export type $SysWidgetλShape = $.typeutil.flatten<_sys_core.$SysObjλShape & {
}>;
type $SysWidget = $.ObjectType<"sys_user::SysWidget", $SysWidgetλShape, null, [
  ..._sys_core.$SysObj['__exclusives__'],
]>;
const $SysWidget = $.makeType<$SysWidget>(_.spec, "507b0cd6-b3c2-11ee-90f1-ff05f1b7241b", _.syntax.literal);

const SysWidget: $.$expr_PathNode<$.TypeSet<$SysWidget, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SysWidget, $.Cardinality.Many), null);

export type $currentUserλShape = $.typeutil.flatten<$SysUserλShape & {
}>;
type $currentUser = $.ObjectType<"sys_user::currentUser", $currentUserλShape, null, [
  ...$SysUser['__exclusives__'],
]>;
const $currentUser = $.makeType<$currentUser>(_.spec, "508c9382-b3c2-11ee-899a-e55ec68708a2", _.syntax.literal);

const currentUser: $.$expr_PathNode<$.TypeSet<$currentUser, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($currentUser, $.Cardinality.Many), null);

type getRootUserλFuncExpr = $.$expr_Function<
  $UserRoot, $.cardutil.overrideLowerBound<$.Cardinality.One, 'Zero'>
>;
function getRootUser(): getRootUserλFuncExpr;
function getRootUser(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_user::getRootUser', args, _.spec, [
    {args: [], returnTypeId: "505f29d6-b3c2-11ee-a534-b73af31574a8", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_user::getRootUser",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getStaffByNameλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
  P2 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysStaff, $.cardutil.overrideLowerBound<$.cardutil.multiplyCardinalities<$.cardutil.paramCardinality<P1>, $.cardutil.paramCardinality<P2>>, 'Zero'>
>;
function getStaffByName<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
  P2 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  firstName: P1,
  lastName: P2,
): getStaffByNameλFuncExpr<P1, P2>;
function getStaffByName(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_user::getStaffByName', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}, {typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "506d1594-b3c2-11ee-8a4e-7313d86159be", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_user::getStaffByName",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getUserλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysUser, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getUser<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  userName: P1,
): getUserλFuncExpr<P1>;
function getUser(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_user::getUser', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "50759917-b3c2-11ee-a6a5-635e27965552", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_user::getUser",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getUserTypeλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysUserType, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getUserType<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  userTypeName: P1,
): getUserTypeλFuncExpr<P1>;
function getUserType(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_user::getUserType', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "5071c13e-b3c2-11ee-b22f-ff2605d1c34f", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_user::getUserType",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type getWidgetλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  $SysWidget, $.cardutil.overrideLowerBound<$.cardutil.paramCardinality<P1>, 'Zero'>
>;
function getWidget<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  widgetName: P1,
): getWidgetλFuncExpr<P1>;
function getWidget(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('sys_user::getWidget', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "507b0cd6-b3c2-11ee-90f1-ff05f1b7241b", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "sys_user::getWidget",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

const $sys_user__globals: {  SYS_USER: _.syntax.$expr_Global<
              // "sys_user::SYS_USER",
              $SYS_USER,
              $.Cardinality.AtMostOne
              >,  SYS_USER_ID: _.syntax.$expr_Global<
              // "sys_user::SYS_USER_ID",
              $SYS_USER_ID,
              $.Cardinality.AtMostOne
              >,  currentUser: _.syntax.$expr_Global<
              // "sys_user::currentUser",
              $currentUser,
              $.Cardinality.AtMostOne
              >,  currentUserId: _.syntax.$expr_Global<
              // "sys_user::currentUserId",
              _std.$uuid,
              $.Cardinality.AtMostOne
              >} = {  SYS_USER: _.syntax.makeGlobal(
              "sys_user::SYS_USER",
              $.makeType(_.spec, "50836d83-b3c2-11ee-8679-3b42549300f4", _.syntax.literal),
              $.Cardinality.AtMostOne) as any,  SYS_USER_ID: _.syntax.makeGlobal(
              "sys_user::SYS_USER_ID",
              $.makeType(_.spec, "50881349-b3c2-11ee-a2ed-1f5ea2f3a678", _.syntax.literal),
              $.Cardinality.AtMostOne) as any,  currentUser: _.syntax.makeGlobal(
              "sys_user::currentUser",
              $.makeType(_.spec, "508c9382-b3c2-11ee-899a-e55ec68708a2", _.syntax.literal),
              $.Cardinality.AtMostOne) as any,  currentUserId: _.syntax.makeGlobal(
              "sys_user::currentUserId",
              $.makeType(_.spec, "00000000-0000-0000-0000-000000000100", _.syntax.literal),
              $.Cardinality.AtMostOne) as any};



export { $Mgmt, Mgmt, $UserRoot, UserRoot, $SysUser, SysUser, $SYS_USER, SYS_USER, $SYS_USER_ID, SYS_USER_ID, $SysStaff, SysStaff, $SysUserType, SysUserType, $SysWidget, SysWidget, $currentUser, currentUser };

type __defaultExports = {
  "Mgmt": typeof Mgmt;
  "UserRoot": typeof UserRoot;
  "SysUser": typeof SysUser;
  "SYS_USER": typeof SYS_USER;
  "SYS_USER_ID": typeof SYS_USER_ID;
  "SysStaff": typeof SysStaff;
  "SysUserType": typeof SysUserType;
  "SysWidget": typeof SysWidget;
  "currentUser": typeof currentUser;
  "getRootUser": typeof getRootUser;
  "getStaffByName": typeof getStaffByName;
  "getUser": typeof getUser;
  "getUserType": typeof getUserType;
  "getWidget": typeof getWidget;
  "global": typeof $sys_user__globals
};
const __defaultExports: __defaultExports = {
  "Mgmt": Mgmt,
  "UserRoot": UserRoot,
  "SysUser": SysUser,
  "SYS_USER": SYS_USER,
  "SYS_USER_ID": SYS_USER_ID,
  "SysStaff": SysStaff,
  "SysUserType": SysUserType,
  "SysWidget": SysWidget,
  "currentUser": currentUser,
  "getRootUser": getRootUser,
  "getStaffByName": getStaffByName,
  "getUser": getUser,
  "getUserType": getUserType,
  "getWidget": getWidget,
  "global": $sys_user__globals
};
export default __defaultExports;
